export const JOBS_FILTER_REQUESTED = 'JOBS_FILTER_REQUESTED';
export const JOBS_FILTER_SUCCEEDED = 'JOBS_FILTER_SUCCEEDED';
export const JOBS_FILTER_FAILED = 'JOBS_FILTER_FAILED';

export const LOAD_JOBS_REQUESTED = 'LOAD_JOBS_REQUESTED';
export const LOAD_JOBS_SUCCEEDED = 'LOAD_JOBS_SUCCEEDED';
export const LOAD_JOBS_FAILED = 'LOAD_JOBS_FAILED';